import os
import cv2
import numpy as np
from flask import Flask, request, jsonify, render_template_string
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model

app = Flask(__name__)

print("Loading Model...")
model = load_model('efficientnet_final_fine_tuned.keras')
print("Model Loaded Successfully!")

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Image Detector</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: #f3f4f6;
            color: #374151;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 40px 20px;
        }
        .container {
            background: white;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
            width: 100%;
            max-width: 600px;
        }
        h1 { text-align: center; margin-bottom: 10px; }
        p { text-align: center; color: #6b7280; margin-bottom: 20px; }
        
        .upload-area {
            border: 2px dashed #d1d5db;
            border-radius: 8px;
            padding: 40px 20px;
            text-align: center;
            cursor: pointer;
            background-color: #f9fafb;
            transition: border 0.3s ease;
        }
        .upload-area:hover { border-color: #3b82f6; }
        .upload-area img { max-width: 100%; max-height: 300px; display: none; margin: 0 auto; border-radius: 8px; }
        .upload-area span { display: block; color: #9ca3af; font-size: 16px; }
        
        .results { margin-top: 20px; display: none; }
        .bar-container {
            background-color: #e5e7eb;
            border-radius: 9999px;
            margin: 10px 0;
            overflow: hidden;
            position: relative;
            height: 30px;
        }
        .bar-fill {
            height: 100%;
            transition: width 0.5s ease-in-out;
            display: flex;
            align-items: center;
            padding-left: 10px;
            color: white;
            font-weight: bold;
            font-size: 14px;
            white-space: nowrap;
        }
        .real-bar { background-color: #10b981; width: 0%; }
        .fake-bar { background-color: #ef4444; width: 0%; }
        
        button {
            display: block;
            width: 100%;
            padding: 12px;
            background-color: #3b82f6;
            color: white;
            border: none;
            border-radius: 8px;
            font-size: 16px;
            font-weight: bold;
            cursor: pointer;
            margin-top: 20px;
        }
        button:hover { background-color: #2563eb; }
        #fileInput { display: none; }
    </style>
</head>
<body>

    <div class="container">
        <h1>AI Image Detector</h1>
        <p>Drop any image here to check if it's Real or generated by AI!</p>
        
        <input type="file" id="fileInput" accept="image/*">
        
        <div class="upload-area" id="dropZone" onclick="document.getElementById('fileInput').click()">
            <span id="uploadText">Click or Drag & Drop an image here</span>
            <img id="previewImage" src="" alt="Preview">
        </div>

        <button id="predictBtn">Analyze Image</button>

        <div class="results" id="resultsArea">
            <div style="display: flex; justify-content: space-between; margin-bottom: 5px;">
                <strong>Real Image</strong>
                <span id="realPercent">0%</span>
            </div>
            <div class="bar-container">
                <div class="bar-fill real-bar" id="realBar"></div>
            </div>

            <div style="display: flex; justify-content: space-between; margin-bottom: 5px; margin-top: 15px;">
                <strong>AI Generated (Fake)</strong>
                <span id="fakePercent">0%</span>
            </div>
            <div class="bar-container">
                <div class="bar-fill fake-bar" id="fakeBar"></div>
            </div>
        </div>
    </div>

    <script>
        const fileInput = document.getElementById('fileInput');
        const dropZone = document.getElementById('dropZone');
        const previewImage = document.getElementById('previewImage');
        const uploadText = document.getElementById('uploadText');
        const predictBtn = document.getElementById('predictBtn');
        const resultsArea = document.getElementById('resultsArea');
        
        let currentFile = null;

        fileInput.addEventListener('change', function(e) { handleFile(e.target.files[0]); });

        dropZone.addEventListener('dragover', (e) => { e.preventDefault(); dropZone.style.borderColor = '#3b82f6'; });
        dropZone.addEventListener('dragleave', () => { dropZone.style.borderColor = '#d1d5db'; });
        dropZone.addEventListener('drop', (e) => {
            e.preventDefault();
            dropZone.style.borderColor = '#d1d5db';
            if (e.dataTransfer.files.length > 0) {
                fileInput.files = e.dataTransfer.files;
                handleFile(e.dataTransfer.files[0]);
            }
        });

        function handleFile(file) {
            if (file && file.type.startsWith('image/')) {
                currentFile = file;
                const reader = new FileReader();
                reader.onload = (e) => {
                    previewImage.src = e.target.result;
                    previewImage.style.display = 'block';
                    uploadText.style.display = 'none';
                    resultsArea.style.display = 'none';
                };
                reader.readAsDataURL(file);
            }
        }

        predictBtn.addEventListener('click', async () => {
            if (!currentFile) { alert("Please select an image first!"); return; }

            predictBtn.innerText = "Analyzing...";
            predictBtn.disabled = true;

            const formData = new FormData();
            formData.append('image', currentFile);

            try {
                const response = await fetch('/predict', { method: 'POST', body: formData });
                const data = await response.json();
                
                if (response.ok) {
                    document.getElementById('realPercent').innerText = data.real.toFixed(2) + '%';
                    document.getElementById('realBar').style.width = data.real + '%';
                    
                    document.getElementById('fakePercent').innerText = data.fake.toFixed(2) + '%';
                    document.getElementById('fakeBar').style.width = data.fake + '%';
                    
                    resultsArea.style.display = 'block';
                } else {
                    alert(data.error || "An error occurred");
                }
            } catch (err) {
                alert("Server connection failed.");
            } finally {
                predictBtn.innerText = "Analyze Image";
                predictBtn.disabled = false;
            }
        });
    </script>
</body>
</html>
"""

@app.route('/', methods=['GET'])
def index():
    return render_template_string(HTML_TEMPLATE)

@app.route('/predict', methods=['POST'])
def predict():
    # 1. استلام الصورة من الواجهة
    if 'image' not in request.files:
        return jsonify({'error': 'No image provided'}), 400
        
    file = request.files['image']
    
    # 2. قراءة الصورة
    file_bytes = np.frombuffer(file.read(), np.uint8)
    img = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)
    
    if img is None:
        return jsonify({'error': 'Invalid image format'}), 400

    # 3. السطر السحري لحل مشكلة الألوان (من BGR لـ RGB)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # 4. تجهيز الصورة للموديل
    img_resized = cv2.resize(img, (300, 300))
    img_array = img_to_array(img_resized)
    img_array = np.expand_dims(img_array, axis=0)
    
    # 5. التوقع
    prediction = model.predict(img_array, verbose=0)[0][0]
    
    real_confidence = float(prediction) * 100
    fake_confidence = float(1.0 - prediction) * 100
    
    return jsonify({
        'real': real_confidence,
        'fake': fake_confidence
    })

if __name__ == '__main__':
    print("Server running at http://127.0.0.1:5000")
    app.run(host='0.0.0.0', port=5000, debug=True)